apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.targetPort }}
  externalIPs:
    - 10.0.0.6
  selector:
    app: {{ include "fullname" . }}